### ISSUE TITLE
Train on my own dataset with only one class

### ISSUE THREAD

**Issue by antocapp** [facebookresearch/maskrcnn-benchmark#112]
## ❓ Questions and Help
Hello, thanks for this great repository. 
I would love to fine tune the model **e2e_mask_rcnn_X_101_32x8d_FPN_1x_caffe2.yaml** on my own dataset and to detect just one class instead of the 81 classes of COCO dataset. 

Could you briefly explain how and where in the code to prune my network outputs and how to organize the dataset? 

Thanks a lot

**Comment by fmassa** [comment]
Hi,

This is a similar question as in https://github.com/facebookresearch/maskrcnn-benchmark/issues/15 , where a number of solutions are proposed there.

In order to avoid duplicate issues, I'm closing this one in favor of https://github.com/facebookresearch/maskrcnn-benchmark/issues/15, but let me know if you have further questions, either by commenting here or in https://github.com/facebookresearch/maskrcnn-benchmark/issues/15.
