### ISSUE TITLE
Mask Postprocessing

### ISSUE THREAD

**Issue by hadim** [facebookresearch/maskrcnn-benchmark#123]
During inference, doing `model(images_tensor)` return a prediction list. The masks returned are of shape `[Nx28x28]` where `N` is the number of objects and `28` is the default mask resolution in the model configuration.

Could the model post-process the mask and returned them resized and correctly located on the input image?

It's ok to post-process the masks after inference with or without the `Masker` class but having it done during inference would be more convenient in my opinion.

**Comment by fmassa** [comment]
Yes, it is possible and was actually what I wanted to do initially.
You can pass the `Masker` object [in here](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/modeling/roi_heads/mask_head/inference.py#L25) so that the result of the model is the already-pasted masks in the image. You just need to modify [this line](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/modeling/roi_heads/mask_head/inference.py#L187) to return a `Masker` instead.

The reason why I didn't do it like that (but instead perform it in two steps) is that at this stage we would be pasting the masks into the resized image (which is bigger than the original image in general). This means that we would be spending some significant time creating a high-resolution mask that would afterwards be resized to match the original input size.

I have a CUDA implementation of the `Masker` that gives almost the same results as the current one, and would allow us to run it in the high-resolution images without having to worry about speed.
But it gives some slightly lower mAP due to some boundary differences, so I removed it for now.

Let me know what you think.

**Comment by hadim** [comment]
Thank you for the explanation.

In my case images are not resized since I am working with microscopy images I don't want to modify the scale of the objects. But I understand your concern about unnecessary computation for a dataset such as COCO.

Since the resizing is done outside of the model during preprocessing in the data loader I don't think it's possible to do the post-processing inside the model. That being said that could model option in the YAML configuration file:

```
def make_roi_mask_post_processor(cfg):
    if cfg.MODEL.ROI_MASK_HEAD.POSTPROCESS_MASK:
        masker = Masker
    else:
        masker = None
    mask_post_processor = MaskPostProcessor(masker)
    return mask_post_processor
```

Let me know if that would work, I can submit a PR. Not that the default should be `MODEL.ROI_MASK_HEAD.POSTPROCESS_MASK = False` so the existing code will still work out-of-the-box.

About the CUDA implementation it could also be an option if mAP is too much different than the CPU version or without being an option it could also be automatically chosen instead of CPU `Masker` if Cuda is available.

**Comment by hadim** [comment]
See https://github.com/facebookresearch/maskrcnn-benchmark/pull/124
