### ISSUE TITLE
Cannot overlay BBoxes and Classes on the final prediction (inference)

### ISSUE THREAD

**Issue by akshaygadipatil** [facebookresearch/maskrcnn-benchmark#147]
## ❓ Questions and Help
I ran the demo.py on pre-trained mask rcnn using weights form here
 "e2e_mask_rcnn_R_101_FPN_1x.yaml" on this image 
![beach](https://user-images.githubusercontent.com/22264995/48389072-c0ea1900-e6b0-11e8-9354-7c7d7f95ec9d.jpg)

The predicted output of inference on this is:
![predicted](https://user-images.githubusercontent.com/22264995/48389313-c6942e80-e6b1-11e8-852b-21167631342c.jpg)

How do I visualize the BBoxes and class information over this prediction?

I used the exact same code in demo.py and predictor.py.

Any pointers would be appreciated.

Thanks.

**Comment by fmassa** [comment]
Hi,

The images have weird color because they are in BGR format, instead of RGB.

This is how I did for [overlaying the class names and predicted boxes](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/demo/predictor.py#L175-L178), and the underlying functions are fairly simple.

I'm closing the issue, but let us know if you have any further questions.

**Comment by akshaygadipatil** [comment]
If you observe carefully, objects of the same class have the same color.
Another example is this:
![predicted](https://user-images.githubusercontent.com/22264995/48461902-da5f9380-e78a-11e8-9c15-12a098760e4f.jpg)

I used RGB notation, not BGR. I used the underlying functions for overlaying boxes and class names but they fail to appear in the inferred image. Do I have to print the boxes to see them in the image?

**Comment by akshaygadipatil** [comment]
@fmassa Am I missing something?

**Comment by fmassa** [comment]
`predictions` is not the image with the boxes drawn, but a `BoxList` object which contains the coordinates of the boxes, as well as other information.

**Comment by akshaygadipatil** [comment]
"predictions" in demo.py , not in predictor.py

**Comment by fmassa** [comment]
Do you mean this file? https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/demo/webcam.py

**Comment by akshaygadipatil** [comment]
I mean this: 
https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/demo/Mask_R-CNN_demo.ipynb

**Comment by akshaygadipatil** [comment]
@fmassa , I am digressing here a bit but I want to train on my own dataset with a different number of classes. Requesting you to pls help me with the following questions:

1) Do I have to prepare a .json file consistent with the coco format?
2) What I did now is create my own dataset (as per the helper function provided), as below:
![image](https://user-images.githubusercontent.com/22264995/48612260-58639c00-e93d-11e8-9156-7004772835df.png)
It correctly loads the data.
But I don't understand how and where to pass this for training?
And in which function should I change the number of classes to suit my data?

Would be of great help if you could point accordingly.

Thanks so much for your patience.

**Comment by fmassa** [comment]
Hi,

Have a look at https://github.com/facebookresearch/maskrcnn-benchmark/pull/131 to see how they added Pascal VOC dataset. There was also some refactoring going on there, so don't be scared about the number of lines changed.

Basically, [you need to import your dataset here](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/data/datasets/__init__.py) so that it's visible in the `datasets` module, and then [extend the paths catalog with the name of your dataset and paths](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/config/paths_catalog.py#L20-L39). The `factory` method is the name of your dataset as it can be seen in `maskrcnn_benchmark.data.datasets`.

**Comment by akshaygadipatil** [comment]
Let me take a look and get back to you.
Appreciate your quick response :)

**Comment by akshaygadipatil** [comment]
I thought[ this](https://github.com/facebookresearch/maskrcnn-benchmark#adding-your-own-dataset) is useful for preparing our own datasets. I prepared my data according to the above link but do not know where to pass it.
Pointers pls.

**Comment by akshaygadipatil** [comment]
Question: So do I need .json files in my data path? 
I have .mat file instead and I used the .mat file to get bbox and class id in class "MyDataset(object)" definition.

**Comment by fmassa** [comment]
You can write your dataset as you want. There is no restriction about JSON.

There is a drawback though as mentioned in the post, which is that evaluation metrics are currently specific to COCO-style datasets, but this is being improved on the Pascal VOC PR.

**Comment by akshaygadipatil** [comment]
Thanks! Appreciate your response and patience.
