### ISSUE TITLE
Support RLE format and binary masks.

### ISSUE THREAD

**Issue by wangg12** [facebookresearch/maskrcnn-benchmark#16]
## 🚀 Feature
Currently the code is based on polygon masks. RLE and binary masks should be supported for general datasets.

**Comment by fmassa** [comment]
I totally agree about binary masks. Indeed, there is a draft implementation in [here](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/structures/segmentation_mask.py#L11-L48) that supports some functionality.

Ideally, I'd want `SegmentationMask` to internally support both `Polygons` and `Masks`, but I didn't do it yet because it was not necessary for the experiments I was performing.

But contributions are more than welcome! :-)

**Comment by wangg12** [comment]
@fmassa For RLE format, we can store it in coco-style json file (Or maybe the paths of binary mask can be stored in json file). Then we can load the json file into memory and convert mask of any format to binary mask, and then do some transformations. I want this feature because sometimes polygons are not very convenient.

**Comment by wangg12** [comment]
@fmassa Agree with you. The internal converting to binary masks is exactly what I want.

**Comment by wangg12** [comment]
Solved by PR #150
