### ISSUE TITLE
In post process mask, why doing expand_masks and expand_box operation?

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/maskrcnn-benchmark#188]
## ❓ Questions and Help

Hi, all, I have some puzzle about post process mask and box. is that, ther are some operation such as:

```
            padded_mask, scale = self.expand_masks(mask[None], padding=1)
            mask = padded_mask[0, 0]
            print(mask)
            box = self.expand_boxes(box[None], scale)[0]
            box = box.numpy().astype(np.int32)

            TO_REMOVE = 1
            w = box[2] - box[0] + TO_REMOVE
            h = box[3] - box[1] + TO_REMOVE
            w = max(w, 1)
            h = max(h, 1)
            mask = Image.fromarray(mask.cpu().numpy())
            mask = mask.resize((w, h), resample=Image.BILINEAR)
            mask = np.array(mask, copy=False)

            cv2.imshow('mm', mask)
            cv2.waitKey()
```

Simply, this is doing a expand (padding) operation on mask and box. But my question is, why doing this? I think this is time consuming and really not neccesary.

**Comment by fmassa** [comment]
Hi,

This expanding happens because there are boundary effects that happens when simply upsampling the masks, and adding this padding solves that. Also worth noting that this is the default behavior of Detectron.

For a better / faster version of this code, check https://github.com/facebookresearch/maskrcnn-benchmark/pull/129 , which implements a dedicated kernel for computing the masks.
It currently gives very similar results to the approach we have now, but the results are not 100% the same, so I haven't merged it yet in master because it decreases mAP for masks by a few points.

Let me know if you have further questions, or if you'd be willing to try helping solve the boundary differences in #129 .

**Comment by jinfagang** [comment]
@fmassa I think I got it, just for mAP calculation more precisely and improve it.
