### ISSUE TITLE
Support for Human Pose Estimation 

### ISSUE THREAD

**Issue by Naman-ntc** [facebookresearch/maskrcnn-benchmark#197]
Hi, human pose estimation is also a standard use of mask rcnn framework. It would be really great if we can extend this benchmark repository for human pose estimation.
[Pytorch Detectron](https://github.com/roytseng-tw/Detectron.pytorch) has implemented it earlier as well. 

Also I would be like to work on this if you guys give me a thumbs up! I have a good survey of [different human pose](https://github.com/Naman-ntc/Pytorch-Human-Pose-Estimation) systems and it would be an interesting assignment for me
Thanks

**Comment by fmassa** [comment]
Hi,

There is an open PR that implement keypoint R-CNN, see https://github.com/facebookresearch/maskrcnn-benchmark/pull/69

It doesn't reproduce exactly the results from Detectron yet, and I hadn't have the time to investigate further. That's why I haven't merged it in master yet.

But it would be awesome if the community could help me find out where the differences in mAP come from!

**Comment by Naman-ntc** [comment]
Ohh alright, I only searched through the issues and didn't find anything related to keypoints. 
I'll also try looking at the PR and sources of differences.

**Comment by fmassa** [comment]
Awesome, thanks!

**Comment by fmassa** [comment]
This has been implemented in https://github.com/facebookresearch/maskrcnn-benchmark/pull/69
