### ISSUE TITLE
Maybe there is some details can be refined

### ISSUE THREAD

**Issue by CoinCheung** [facebookresearch/maskrcnn-benchmark#221]
1. https://github.com/facebookresearch/maskrcnn-benchmark/blob/ef8a93b10317ec0f26f1567860f216df270fa0df/maskrcnn_benchmark/engine/inference.py#L20
 
Maybe this line could be changed from `tqdm(enumerate(data_loader))` to `enumerate(tqdm(data_loader))`.

2. Maybe we could update readme. The inference with a few line example should replace `from predictor import COCODemo` to `from demo.predictor import COCODemo`.

**Comment by fmassa** [comment]
Hi,

1. I actually think we should remove `tqdm` altogether, and have some custom logging. I added it early in the beginning to have some metrics, but they don't log nicely.
2. The demo currently only works if you run it from the `demo` folder (because of the imports), so it would not work if run from the root folder.
