### ISSUE TITLE
FPN LastLevelMaxPool()

### ISSUE THREAD

**Issue by lg-zhang** [facebookresearch/maskrcnn-benchmark#244]
## ❓ Questions and Help
I notice that in FPN the lowest resolution feature map undergoes a pooling operation defined in
LastLevelMaxPool()() which is implemented as:
```
class LastLevelMaxPool(nn.Module):
    def forward(self, x):
        return [F.max_pool2d(x, 1, 2, 0)]
```
But the second argument of max_pool2d() is the kernel_size, so what this function essentially does is to pick every other pixel in the input (i.e., not max pooling). Is this what it is supposed to do? Thanks!

**Comment by fmassa** [comment]
Yes, this is intended and follows the implementation from Detectron in https://github.com/facebookresearch/Detectron/blob/master/detectron/modeling/FPN.py#L229

The reason is just to have a smaller input and thus larger receptive field for larger boxes. There is some more information about this in the FPN paper.

**Comment by victor000000** [comment]
as the note said:

1 Here we introduce P6 only for covering a larger anchor scale of 5122.
P6 is simply a stride two subsampling of P5. P6 is not used by the Fast
R-CNN detector in the next section.
