### ISSUE TITLE
Is train visualization available?

### ISSUE THREAD

**Issue by txytju** [facebookresearch/maskrcnn-benchmark#249]
## ❓ Questions and Help
Thanks for your great work! I haven't found any training visualization tools like visdom or tensorboardX.  So how can I know that my training has converged？ And how can I save training prameters for futher comparision?

**Comment by fmassa** [comment]
There is an open PR that adds support for TensorBoardX, see https://github.com/facebookresearch/maskrcnn-benchmark/pull/163

Apart from that, you can also parse the logs that are saved in order to plot your curves.

Training parameters are logged in the logs, and usually they are all coming from the configuration files, so that it becomes very easy to rerun existing jobs.
