### ISSUE TITLE
Question about IterationBasedBatchSampler

### ISSUE THREAD

**Issue by bowenc0221** [facebookresearch/maskrcnn-benchmark#292]
## ❓ Questions and Help
Hi @fmassa, I'm a little lost in the implementation of IterationBasedBatchSampler. Could you please explain a little bit about it?

1. why you call set_epoch every iteration by the iteration number?
2. how do you reset the iterator after every epoch?

Thanks.

**Comment by fmassa** [comment]
Hi,

To answer your questions:
1 - we call `set_epoch` so that we change the random seed from the samplers in each process. This is necessary to avoid having the same order of examples coming after the first dataset epoch
2 - the original iterator is reset in https://github.com/facebookresearch/maskrcnn-benchmark/blob/61ffdb3803db562c23d883439aee16e599c051e6/maskrcnn_benchmark/data/samplers/iteration_based_batch_sampler.py#L24

Once an epoch (given by the `batch_sampler`) is over, it will create a new iterator there.

Does this answer your questions?

**Comment by bowenc0221** [comment]
Thanks! Your answer is very helpful! I understand how it works now.
