### ISSUE TITLE
Need help regarding training parameters

### ISSUE THREAD

**Issue by Prabhat-IIT** [facebookresearch/maskrcnn-benchmark#352]
I want to train maskrcnn on [Uber-text dataset](https://s3-us-west-2.amazonaws.com/uber-common-public/ubertext/index.html) which has 110K images of size 1kX1k and 4kX4k.
So, I followed these steps for training:
1. Convert my dataset to coco format using pycococreator tool
2. Named jsons files similar to coco dataset `instances_something.json`
3. For using Detectron pretrained weights I used [`tools/trim_detectron_model.py`](https://gist.github.com/wangg12/aea194aa6ab6a4de088f14ee193fd968)
4. Start training maskrcnn by changing weight path

But I've only one K80 Gpu to train it and it'll take a very long time to train..approx 11 days for one epoch. @fmassa  Can you suggest some changes to training parameters for efficient training and could you suggest appropriate ec2 instance p3.2x or p3.8x or p3.16x large for training in atleast a week.

**Comment by fmassa** [comment]
The Uber-text dataset seems sufficiently different from COCO so that I'm not sure that transfer learning will help there.
In order to speed things up, you could try reducing the size of the images in https://github.com/facebookresearch/maskrcnn-benchmark/blob/d28845e112de36781b2b5f7217a34b2b62de8d2f/maskrcnn_benchmark/config/defaults.py#L40-L42
This will make training faster (but the quality of the results will be worse).
You can also reduce the number of iterations, even though it will decrease the quality of the results.

Also, know that the 11 days is probably for the end of training to happen.

**Comment by noobgrow** [comment]
@Prabhat-IIT Could you please paste the trim_detectron_model.py code? I cant open the link in China
