### ISSUE TITLE
Buffer has wrong number of dimensions when converting to RLE

### ISSUE THREAD

**Issue by adizhol** [facebookresearch/maskrcnn-benchmark#382]
## ❓ Questions and Help
[loss.py : 44]
`    mask = scaled_mask.convert(mode="mask")` 
```
File "D:\UVEye\firstpass_maskrcnn\maskrcnn_benchmark\structures\segmentation_mask.py", line 129, in convert
    [p.numpy() for p in self.polygons], height, width
  File "pycocotools\_mask.pyx", line 295, in pycocotools._mask.frPyObjects
  File "pycocotools\_mask.pyx", line 265, in pycocotools._mask.frPoly
ValueError: Buffer has wrong number of dimensions (expected 1, got 2)

```
scaled_mask is:
`Polygons(num_polygons=1, image_width=28, image_height=28, mode=None)`
scaled_mask.polygons is a list of tensors (len = 1),
scaled_mask.polygons[0].shape = torch.Size([104, 1])

I'm using a custom dataloader, so I'm probably doing something wrong. But what?

Thanks!

**Comment by fmassa** [comment]
Hi,

I believe the polygons should have 2 elements in the second dimension, you only have one?

**Comment by SilvioGiancola** [comment]
Hi, I encountered a similar error but with a size of 3. Is there any documentation on how to build the mask for a custom dataset? My error originates from [loss.py](https://github.com/facebookresearch/maskrcnn-benchmark/blob/5f2a8263a1a0f2f5f0137042cd4ba64efcb6859a/maskrcnn_benchmark/modeling/roi_heads/mask_head/loss.py#L40) due to an error in the `frPyObjects` function in [segmentation_mask.py](https://github.com/facebookresearch/maskrcnn-benchmark/blob/5f2a8263a1a0f2f5f0137042cd4ba64efcb6859a/maskrcnn_benchmark/structures/segmentation_mask.py#L129):

```
  File "/home/giancos/git/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/mask_head/loss.py", line 41, in project_masks_on_boxes
    mask = scaled_mask.convert(mode="mask")
  File "/home/giancos/git/maskrcnn-benchmark/maskrcnn_benchmark/structures/segmentation_mask.py", line 192, in convert
    [p.numpy() for p in self.polygons], height, width
  File "pycocotools/_mask.pyx", line 295, in pycocotools._mask.frPyObjects
  File "pycocotools/_mask.pyx", line 265, in pycocotools._mask.frPoly
ValueError: Buffer has wrong number of dimensions (expected 1, got 3)
```

for me `scaled_mask.polygons[0].shape = torch.Size([85, 1, 2])`

`scaled_mask.polygons` looks like:

```
 [tensor([[[ 52.2815,  54.4385]],

        [[-48.1267, -49.5029]],

        [[ 53.3600,  53.3600]],

   ...

        [[-46.0625, -50.1909]],

        [[ 51.7422,  54.4385]]])]
```

and `[p.numpy() for p in self.polygons]` looks like this:

```
 [array([[[ 52.281452,  54.438488]],

       [[-48.12671 , -49.50286 ]],

       [[ 53.35997 ,  53.35997 ]],


   ...


       [[-46.06248 , -50.190937]],

       [[ 51.742195,  54.438488]]], dtype=float32)]

```

Also, I am using this config [file](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/configs/e2e_mask_rcnn_R_50_FPN_1x.yaml) with a custom dataset. I guess I have an issue with how I define my mask in my custom dataset, so I'll be happy to be redirected to some documentation on the topic.

Thanks

**Comment by fmassa** [comment]
@SilvioGiancola there is some information on the COCO format in http://cocodataset.org/#format-data
In your case, you should probably just have a shape of `[85, 2]` instead of `[85, 1, 2]` I think

**Comment by supernashg** [comment]
https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/_mask.pyx#:~:text=def%20frPyObjects(pyobj%2C%20h%2C%20w)%3A
Look into the source code above can help!

**Comment by northeastsquare** [comment]
<img width="646" alt="image" src="https://github.com/facebookresearch/maskrcnn-benchmark/assets/3086078/b223e10c-bbdb-470e-a091-60963d1f421a">
points should be flatten
