### ISSUE TITLE
about RPN loss

### ISSUE THREAD

**Issue by JoyHuYY1412** [facebookresearch/maskrcnn-benchmark#431]
## ❓ Questions and Help In the paper of maskrcnn, it says

> For convenient ablation, RPN is trained separately and does not share features with Mask R-CNN, unless specified.

As I understand your code, if you want to train RPN only, you just use the proposals genetated by RPN, select them according to Neg/Pos samples ratio and calculate loss.
But if you want to train the model end-to-end, which means train the heads with RPN, the loss of RPN doesn't change but the loss of heads will only be calculated of some boxes (after RPN regress and selected after NMS) with a fix Neg/Pos ratio.

Am I right?
BTW, does that mean after RPN and NMS, there are still Positive and Negative boxes? Why NMS still leaves Negative boxes remain?

**Comment by fmassa** [comment]
Hi,

The quote that you have is not relevant to the implementation in this repo. Indeed, the RPN and the boxes / masks are trained jointly in an end-to-end fashion.

If you just want to train the RPN, I'd recommend having a look at the [config files for the RPN-only](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/configs/rpn_R_50_C4_1x.yaml).

> As I understand your code, if you want to train RPN only, you just use the proposals genetated by RPN, select them according to Neg/Pos samples ratio and calculate loss.
But if you want to train the model end-to-end, which means train the heads with RPN, the loss of RPN doesn't change but the loss of heads will only be calculated of some boxes (after RPN regress and selected after NMS) with a fix Neg/Pos ratio.

Yes, that's correct. We keep a 0.25/0.75 ratio for training the boxes, as in R-CNN.

> BTW, does that mean after RPN and NMS, there are still Positive and Negative boxes?

Don't forget that the RPN generates many (10s of thousands) of proposals, and many of them have low objectness score because there is a small overlap with an object.

> Why NMS still leaves Negative boxes remain?

If a bounding box is away from a ground-truth, it will have a low IoU, and even if it's score is low, it won't be removed by NMS.

I'm closing this issue, but let me know if you have further questions.

**Comment by JoyHuYY1412** [comment]
> Hi,
> 
> The quote that you have is not relevant to the implementation in this repo. Indeed, the RPN and the boxes / masks are trained jointly in an end-to-end fashion.
> 
> If you just want to train the RPN, I'd recommend having a look at the [config files for the RPN-only](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/configs/rpn_R_50_C4_1x.yaml).
> 
> > As I understand your code, if you want to train RPN only, you just use the proposals genetated by RPN, select them according to Neg/Pos samples ratio and calculate loss.
> > But if you want to train the model end-to-end, which means train the heads with RPN, the loss of RPN doesn't change but the loss of heads will only be calculated of some boxes (after RPN regress and selected after NMS) with a fix Neg/Pos ratio.
> 
> Yes, that's correct. We keep a 0.25/0.75 ratio for training the boxes, as in R-CNN.
> 
> > BTW, does that mean after RPN and NMS, there are still Positive and Negative boxes?
> 
> Don't forget that the RPN generates many (10s of thousands) of proposals, and many of them have low objectness score because there is a small overlap with an object.
> 
> > Why NMS still leaves Negative boxes remain?
> 
> If a bounding box is away from a ground-truth, it will have a low IoU, and even if it's score is low, it won't be removed by NMS.
> 
> I'm closing this issue, but let me know if you have further questions.

thank you~
so do you mean there are still many negative boxes after NMS and for detection you choose some to make the number of them is three times of the number of positive boxes after NMS? 
Thank you again for being so patient ^_^

**Comment by fmassa** [comment]
Yes,  we balance the number of positive and negatives during training of the boxes.
This balance is important because there is in general much more negative boxes than positive boxes.
