### ISSUE TITLE
How to perform the evaluation for a single category?

### ISSUE THREAD

**Issue by mr2901** [facebookresearch/maskrcnn-benchmark#461]
## ❓ Questions and Help
![image](https://user-images.githubusercontent.com/11147292/52994837-73b5da00-344b-11e9-8b0d-09fed4df05d1.png)

The result of MaskRCNN is all category.
How to perform the evaluation for a single category?

Thanks

**Comment by fmassa** [comment]
The model is evaluated on all categories that are contained in your dataset.

If you want to modify the evaluation to only display information about one class, I think you can modify
https://github.com/facebookresearch/maskrcnn-benchmark/blob/f8b0118392aae793771cfc6cd869ad0a601d5c92/maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py#L319-L322

and [specify `catIds` in COCOeval](https://github.com/cocodataset/cocoapi/blob/ed842bffd41f6ff38707c4f0968d2cfd91088688/PythonAPI/pycocotools/cocoeval.py#L24) so that you select only a subset of classes to evaluate.

I'd recommend having a look at `cocoeval.py` to figure out how to pass this parameter, should be related to the [Params class](https://github.com/cocodataset/cocoapi/blob/ed842bffd41f6ff38707c4f0968d2cfd91088688/PythonAPI/pycocotools/cocoeval.py#L499)

I'm closing this as this is not really related to `maskrcnn-benchmark`, but let me know if you have further questions

**Comment by watertianyi** [comment]
@fmassa 
How to label a single category with labelme and instance segmentation? There are cat, cat, cat, cat0, cat1, cat2 or cat-0, cat-1, cat-2, etc. which annotation method is used?thank you!

I use cat-0, cat-1, cat-2 for annotation, and use labelme2coco to convert annotations.json, where the annotation is [], what's the matter?
