### ISSUE TITLE
About the loss of masks

### ISSUE THREAD

**Issue by JoyHuYY1412** [facebookresearch/maskrcnn-benchmark#468]
In your code, when calculating the loss for mask prediction, you crop the ground truth mask so it fits in the predicted box. Why don't you resize the mask predicted to the original image's size, and then calculate loss with ground truth mask in original size? So that if the groundtruth mask has some part outside the predicted box, it will still calculate the loss for this part, which I think can help train the box prediction better?

**Comment by fmassa** [comment]
Hi,

Note that this crop is performed in the polygon space, so that there is no loss in accuracy by doing this crop (due to discretization)
Also, we would need to paste the predicted mask into the box location in the original image, to compute the loss over the whole image.
This would not only be a bit more costly, but also a huge part of the elements would be zero, and it could bias the loss to look better than it actually is.

The way I implemented it here follows closely what was implemented in Mask R-CNN (and Detectron).
There are definitely other ways of doing it, but for the sake of reproducibility, I'm keeping the original implementation.
