### ISSUE TITLE
error after defining new layer 

### ISSUE THREAD

**Issue by JoyHuYY1412** [facebookresearch/maskrcnn-benchmark#478]
## ❓ Questions and Help
I defined a new layer called `sem_roi_head.feature_extractor.sem_mask_fcn1.bias` , however, it says 

> maskrcnn_benchmark.utils.model_serialization  INFO: sem_roi_head.feature_extractor.sem_mask_fcn1.bias   loaded from mask_fcn1.bias         of shape (256,)

and load parameters from a layer in mask_head, which causes size mismatch.

I don't know why it happens, and after I rename the layer as `sem_mask1_fcn1`, the error doesn't appear.

Could you please help me with this problem?

**Comment by fmassa** [comment]
This happens because of the way `align_and_update_state_dict` works, see
https://github.com/facebookresearch/maskrcnn-benchmark/blob/b23eee0cb72af70f4e4a72e73537f0884cfd1cff/maskrcnn_benchmark/utils/model_serialization.py#L10-L23

The solution for now is to either remove `mask_fcn1.bias` from the checkpoint or to rename your layer so that there is no name conflict.
