### ISSUE TITLE
Why are we averaging loss over all iterations

### ISSUE THREAD

**Issue by muzammil360** [facebookresearch/maskrcnn-benchmark#531]
## ❓ Questions and Help
I noticed in log file that loss values are median of last 20 iterations and value in bracket contains global average of loss. This is also visible [here](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/utils/metric_logger.py). Now global average definately looks more smooth and gives the impression of training (I know it's training because I get a mAP50=0.42 on val set with 90k iterations on 1 GPU), however, I don't understand if it is the right way to look at training error. How is it a good idea to average it out over all the iterations?

![image](https://user-images.githubusercontent.com/20393633/53821262-69133e80-3f3b-11e9-8031-4eff6b426bb2.png)

Secondly, I am manually parsing the log and plotting. Is there any existing tool that can help me visualize the training error?

**Comment by fmassa** [comment]
Hi,

I'm using the global avg mainly because that's what there was in Detectron, but I agree it smooths a lot the values. You can probably change this to something else, like a larger running average.

About parsing the logs, that's one option, another one is trying out the TensorBoard logger from #163 
Let me know if you have further questions
