### ISSUE TITLE
How to run '-m torch.distributed.launch' if I do training in Jupiter notebook 

### ISSUE THREAD

**Issue by YubinXie** [facebookresearch/maskrcnn-benchmark#538]
## ❓ Questions and Help
The notebook is having errors when I give gpu number more than 2. 

```
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set
```

This error seems from not have `-m torch.distributed.launch`; But how to make it run in jupyter notebook? 

Thanks!

**Comment by fmassa** [comment]
I'm not sure there is an easy way of launching multi-gpu training with the current implementation inside a jupyter notebook, without modifying the codebase to use `torch.multiprocessing.spawn` and potentially facing slowdowns.

**Comment by YubinXie** [comment]
So what you meant is that we should always train with python script instead?

**Comment by fmassa** [comment]
yes, this codebase was not intended to be trained on multiple GPUs from a notebook.

**Comment by YubinXie** [comment]
Got it. Thanks!

**Comment by maomaochongchh** [comment]
@YubinXie Hello, so what should I do if I want to use multi-gpus? Thank you very much.

**Comment by YubinXie** [comment]
Well, if you did not read the above conversion, the take-home message is: no multiple gpu training in notebook; you can only use multiple gpu with given python scripts.

**Comment by maomaochongchh** [comment]
Thanks for your reply! I read it, I did not run in jupyter notebook. I  train with python script, but it always use a single gpu. I notice that problem happened because in train_net.py:
`
num_gpus = int(os.environ["WORLD_SIZE"]) if "WORLD_SIZE" in os.environ else 1
distributed = num_gpus > 1
if distributed:
        torch.cuda.set_device(args.local_rank)
        torch.distributed.deprecated.init_process_group(
            backend="nccl", init_method="env://"
        )
`
num_gpus is always 1, when I change it to 4 directly, the error below happened：
`
Traceback (most recent call last):
  File "/home/chh/Code/github_maskscoring_rcnn-master/maskscoring_rcnn/tools/test_net.py", line 95, in <module>
    main()
  File "/home/chh/Code/github_maskscoring_rcnn-master/maskscoring_rcnn/tools/test_net.py", line 46, in main
    backend="nccl", init_method="env://"
  File "/home/chh/anaconda2/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/distributed/deprecated/__init__.py", line 101, in init_process_group
    group_name, rank)
RuntimeError: rank is not set but it is required for env:// init method at /opt/conda/conda-bld/pytorch-nightly_1552799380021/work/torch/lib/THD/process_group/General.cpp:20
`
I have not solved the error, do you have some advice? Thank you!

**Comment by lihkinVerma** [comment]
How to do the setup for distributed training is defined here by PyTorch -> https://huggingface.co/blog/pytorch-ddp-accelerate-transformers

But you could also do the setting up by adding following lines to your code
import os
os.environ['MASTER_ADDR'] = 'localhost'
os.environ['MASTER_PORT'] = '12355'
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3"
dist.init_process_group(backend='nccl', init_method='env://', rank = torch.cuda.device_count(), world_size = 1)
