### ISSUE TITLE
build error: error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by githubgsq** [facebookresearch/maskrcnn-benchmark#567]
## ❓ Questions and Help
hi, all, I'm building the latest maskrcnn version and encountered the problem as follows:
![image](https://user-images.githubusercontent.com/23164715/54340148-af6e4900-4671-11e9-9e3e-5a13148bf045.png)
I'm using python3.6.6, pytorch1.0.0, gcc/g++ 5.4,
 ps. I can successfully build the version downloaded two weeks ago, it's weird. what happened to the new version?

**Comment by LeviViana** [comment]
This is normal, there have been some changes in PyTorch recently, please refer to [this thread](https://github.com/facebookresearch/maskrcnn-benchmark/pull/557).

Basically, you've got to install a nightly version of PyTorch. In the [official website](https://pytorch.org/) you have some instruction on how to install a nightly version.

**Comment by githubgsq** [comment]
@LeviViana ok, thanks a lot, I'm trying to install pytorch-nightly.

**Comment by githubgsq** [comment]
I installed pytorch-nightly, and maskrcnn-benchmark can be successfully installed now.
however, I encountered another problem, which indicates that:
![image](https://user-images.githubusercontent.com/23164715/54362468-efe6ba80-46a3-11e9-90d2-35b23fecb5c4.png)
I found a related issue here: https://github.com/facebookresearch/maskrcnn-benchmark/issues/367 and ensured the nvcc and cuda are if the same version. 
Same error still.
Then opened setup.py and found I didn't set CUDA_HOME.
please set your CUDA_HOME and rebuild it, succeed now!
If you have similar questions as I met, I hope this share could help.

**Comment by jerpint** [comment]
Since the original error was pasted in an image, it was hard for me to find it via google. I am reposting it here with a temporary solution.

```
/home/jerpint/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.cpp: In lambda function:
/home/jerpint/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.cpp:242:47: error: invalid initialization of reference of type 'const at::Type&' from expression of type 'c10::ScalarType'
   AT_DISPATCH_FLOATING_TYPES(input.scalar_type(), "ROIAlign_forward", [&] {
                                               ^
/miniconda/lib/python3.6/site-packages/torch/lib/include/ATen/Dispatch.h:15:32: note: in definition of macro 'AT_DISPATCH_FLOATING_TYPES'
     const at::Type& the_type = TYPE;                                         \
                                ^
error: command 'gcc' failed with exit status 1
```

In my case, using a nightly version isn't ideal, since I am using this inside a container for other projects and would like to avoid switching to the nightly build if possible for the time being.

The only temporary workaround I can suggest for now is checking out master before the change was introduced, which at the time of writing this post was only a few days ago. This is not an ideal long-term solution.

To checkout `master` before the changes, do

`git checkout 90080e60cc4a9252d019f475af044c9d4119b09b`, 

which is the last commit before the change that requires the nightly pytorch build. You should then be able to compile as expected.
