### ISSUE TITLE
How to ensure the polygon point in the range of proposal box?

### ISSUE THREAD

**Issue by auroua** [facebookresearch/maskrcnn-benchmark#592]
## ❓ Questions and Help
In the `maskerrcnn` paper the mask target is defined as the intersection between an RoI and its associated ground-truth mask. 
But in the code  `segmentation_mask.py` , the method of `Polygons` as defined as following:
```
    def crop(self, box):
        w, h = box[2] - box[0], box[3] - box[1]

        # TODO chck if necessary
        w = max(w, 1)
        h = max(h, 1)

        cropped_polygons = []
        for poly in self.polygons:
            p = poly.clone()
            p[0::2] = p[0::2] - box[0]  # .clamp(min=0, max=w)
            p[1::2] = p[1::2] - box[1]  # .clamp(min=0, max=h)
            cropped_polygons.append(p)

     return Polygons(cropped_polygons, size=(w, h), mode=self.mode)
```
The code that used to constraint the polygon point in the range of proposal box is commented.

`p[0::2] = p[0::2] - box[0] # .clamp(min=0, max=w)`

How to ensure the polygon point is in the range of proposal box?

**Comment by fmassa** [comment]
Hi,
We don't use the clamp because it would modify the shape of the polygon.
Indeed, if we were to use the clamp, we would need to add new vertices to the polygon in order for it to exactly represent what we want.

Given that this is not easy to do, it's just simpler to let the polygons go out of the image boundary, and let the rasterization code (which works with negative values) do it for us.

**Comment by auroua** [comment]
@fmassa  Thanks for your reply. I can't find the rasterization code. The proposal sub-sampled in `roi box head` is sent to `mask head` in which the proposal with positive label is selected and the positive proposal matched with the target box again with the threshold value 0.5. I can't find any more code is used to filter the proposal. Can you help me to point out the related code. Thanks.
