### ISSUE TITLE
i want to only train RPN for objectness detection, no need for classification, do there has any guide or experience?

### ISSUE THREAD

**Issue by mlinxiang** [facebookresearch/maskrcnn-benchmark#65]
## ❓ Questions and Help

in my project, i only want to detect out object but no need to know is label, so i want to use this code to train a rpn network, can share any guide or experience？

**Comment by fmassa** [comment]
Hi,

You basically need to set the `RPN_ONLY` option to true. I'll add a config file for RPN only networks, I forgot to do it last week

**Comment by mlinxiang** [comment]
@fmassa thanks for reply，ok i try this first, expect your more detail information

**Comment by fmassa** [comment]
You need to modify the number of images per bat h plus a few other hyper parameters when using a single GPU. Please look at the README on the section Single GPU training for more information

**Comment by jinzhenhh** [comment]
Hi, @fmassa 
i got this error when i run` test_net.py` by setting 'RPN-Only = True'(i had trained the model by 'RPN-Only'), 
'
  File "/home/deepin/projects/maskrcnn-benchmark/maskrcnn_benchmark/engine/inference.py", line 220, in evaluate_box_proposals
    gt_overlaps = torch.cat(gt_overlaps, dim=0)

RuntimeError: expected a non-empty list of Tensors'

and i just couldn't find out what was wrong, can you help me please?

**Comment by fmassa** [comment]
@jinzhenhh the possibilities I see are the following:
1. you don't have any GT in your test dataset
2. you don't have any prediction from the model, for none of the images

I think the reason is 2. This might have happened due to a too-high learning rate, and your outputs are all NaN or inf for example.

**Comment by jinzhenhh** [comment]
> @jinzhenhh the possibilities I see are the following:
> 
> 1. you don't have any GT in your test dataset
> 2. you don't have any prediction from the model, for none of the images
> 
> I think the reason is 2. This might have happened due to a too-high learning rate, and your outputs are all NaN or inf for example.

@fmassa thanks very much for your reply! I don't have many training images in my  dataset, so i guess it is the reason 2. according to your reply, and now I am training the model by lower learning rate... 
thanks for your reply again!

**Comment by LU4E** [comment]
when i add the config 
`RPN_ONLY: True`

`/anaconda3/envs/pytorch10/lib/python3.7/site-packages/torch/nn/modules/module.py", line 518, in __getattr__
    type(self).__name__, name))
AttributeError: 'CombinedROIHeads' object has no attribute 'box'`
it will break like this

**Comment by fmassa** [comment]
@LU4E can you try one of the configs from https://github.com/facebookresearch/maskrcnn-benchmark/pull/66 ?

**Comment by LU4E** [comment]
it works.
but does this config have the mask branch?

**Comment by LU4E** [comment]
yes. because i have only one class.
the other question is i have many picture which doesn't have any thing.

the problem i face now is this:
`2018-12-10 21:25:55,048 maskrcnn_benchmark.trainer INFO: Start training
box loss is 0.018756842240691185
obj loss is 0.6718491315841675
box loss is 0.0031309775076806545
obj loss is 0.5818259716033936
box loss is 0.006792054045945406
obj loss is 0.42098698019981384
box loss is 0.003268709871917963
obj loss is 0.3997362554073334
box loss is 0.0055918013677001
obj loss is 0.5054059028625488
box loss is 39.254791259765625
obj loss is 9.234609603881836
box loss is inf
obj loss is nan
box loss is inf
obj loss is nan
box loss is nan
obj loss is nan
box loss is nan
obj loss is nan
box loss is nan
obj loss is nan
box loss is nan`
the loss is become nan, which box_loss and objectness_loss is -inf or inf.

**Comment by fmassa** [comment]
your learning rate is probably too large.
About pictures not having anything, either you filter them out of the dataset, or you'll need to modify the library to handle images without objects.

**Comment by fmassa** [comment]
The output of your model being inf might probably come from a gradient that is inf at some point in the previous iteration, that made the weight be inf.
I'd say to try to reduce the learning rate by a factor of 2 or 5, and see if the training goes to nan or not.
