### ISSUE TITLE
Is there a score threshold in RPN only training?

### ISSUE THREAD

**Issue by opoppo** [facebookresearch/maskrcnn-benchmark#689]
## ❓ Questions and Help
I followed the RPN only config but got a precision close to 0.  It seems the proposed boxes are not filtered by a score threshold like in ROI_HEAD.SCORE_THRESH and thus there are always a maximum possible number of boxes.
Is there any configuration to handle this or i need to do some coding here?

**Comment by fmassa** [comment]
No, we always filter RPN via a maximum number of boxes, see https://github.com/facebookresearch/maskrcnn-benchmark/blob/1714b7c20d919f8c536a577e15ba3a03ce733cde/maskrcnn_benchmark/config/defaults.py#L148-L161

You could change the code where those parameters are used in order to set a limit on the threshold, but I believe you'll might end up having a lot of boxes.
