### ISSUE TITLE
Inference ignores OUTPUT_DIR

### ISSUE THREAD

**Issue by DmitryUlyanov** [facebookresearch/maskrcnn-benchmark#92]
## 🐛 Bug

Hi, thanks for fast mask rcnn lib (and very clean code). 

When OUTPUT_DIR is set in the cfg, it is ignored during inference and model is initialized from pretrained Imagenet or similar. The worst thing it does not report it to you, and the code runs fine, but does not predict a thing. 

You either need to pass `save_dir` in here https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/tools/test_net.py#L63 or in the constructor, when parent class is initialized. I do not know which way is better, so not submitting a PR.

**Comment by fmassa** [comment]
Hi,

Thanks for opening the issue.

So, the story about inference and `OUTPUT_DIR` is supposed to be the following: if there is a checkpoint in the directory specified by `OUTPUT_DIR`, it will be used instead of `MODEL.WEIGHT`, see 
https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/utils/checkpoint.py

Now, it might be the case that I'm missing some case here, and I'll be more than happy to fix it.

Do you have the `last_checkpoint` file in your `OUTPUT_DIR`?

**Comment by mlinxiang** [comment]
i have the same problem , and i solve by simple modify follow code predictor.py otherwise the checkpoint check path always "last_checkpoint"
![image](https://user-images.githubusercontent.com/6283983/47889427-e42cf100-de84-11e8-8bc4-c0e11cce6f88.png)

**Comment by DmitryUlyanov** [comment]
@fmassa Besides reusing the latest checkpoint from `OUTPUT_DIR` all new checkpoints of the model are saved to `OUTPUT_DIR`. 

Please compare https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/tools/train_net.py#L50 and https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/tools/test_net.py#L63 . In the first case you set `save_dir` and checkpointer works as expected and starts from the last checkpoint in the `OUTPUT_DIR`, in the second it starts from `MODEL.WEIGHT`.

**Comment by fmassa** [comment]
@DmitryUlyanov oh, I totally missed that!

Yes, we should add the `save_dir` in the constructor, that was an oversight from me, thanks a lot for spotting it!

Could you send a PR fixing it?
Thanks!

**Comment by fmassa** [comment]
I'll send a PR, don't worry
