### ISSUE TITLE
what is the dataset for the pretrained models?

### ISSUE THREAD

**Issue by jpchen** [facebookresearch/maskrcnn-benchmark#990]
I might be missing something completely obvious, but what dataset are the models in the [model zoo](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/MODEL_ZOO.md) trained on? coco? imagenet? i can't find it anywhere, i'm not sure why it isn't documented anywhere

**Comment by SkeletonOne** [comment]
In my opinion, As the config shows, cfg.MODEL.WEIGHT is "catalog://ImageNetPretrained/MSRA/R-50", for example, so it should be ImageNet.

**Comment by as1392** [comment]
They run and give good results on MS COCO, so it must be MS COCO(though I couldn't find any document mentioning this)

**Comment by fmassa** [comment]
From https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/MODEL_ZOO.md#end-to-end-faster-and-mask-r-cnn-baselines

> All the baselines were trained using the exact same experimental setup as in Detectron

And from Detectron MODEL_ZOO https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md#common-settings-and-notes

> All models and results below are on the COCO dataset.

I'd be happy to merge a PR adding this detail to the model zoo.

**Comment by jyf588** [comment]
@as1392 I also feel like catalog://ImageNetPretrained/MSRA/R-50 is the trained COCO weight since outputs good predictions on COCO images. 
But if this is true, https://github.com/facebookresearch/maskrcnn-benchmark/blame/master/README.md#L133 would be telling us to train our own COCO model starting from trained COCO weights, which does not make sense.
Is there something that I misunderstood?
